version: '3.9'

services:

  redis-node-1:
    image: redis:7.2.4
    container_name: redis-node-1 
    command: redis-server --port 6379 --bind 0.0.0.0 --requirepass password --masterauth password --protected-mode no
    restart: always
    volumes:
      - redis-node-1-data:/data
    ports:
      - "7000:6379"

volumes:
  redis-node-1-data:
