mongodb:
  uri: mongodb://root:password@host.docker.internal:27117,host.docker.internal:27118/
  database: linkZapURL

redis:
  addrs:
    - host.docker.internal:7000
    - host.docker.internal:7001
    - host.docker.internal:7002
    - host.docker.internal:7003
    - host.docker.internal:7004
    - host.docker.internal:7005
  password: ""
  db: 0