name: Go CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.19'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run golint
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Run tests
      run: go test ./...
